### ISSUE TITLE
Add support for AbortSignal

### ISSUE THREAD

**Issue by jrencz** [aurelia/fetch-client#102]
**I'm submitting a feature request**

* **Library Version:**
1.3.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13.3

* **Node Version:**
8.9.1

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
n/a

* **Browser:**
Chrome 66 (as of today: Canary) | Firefox 57 | Edge 16
(ones that do have `AbortSignal` implemented)

* **Language:**
all

**Current behavior:**
`signal` is unknown to `RequestInit` type. It's not handled in any special way. In particular: `AbortSignal` instance passed to `init` param of `HttpClient#fetch` is not transferred to `init` param of `WindowOrWorkerGlobalScope.fetch`.

**Expected/desired behavior:**

`signal` passed to `RequestInit` (2nd argument of `HttpClient#fetch`) will affect requests done with fetch-client.

* **What is the expected behavior?**
Behavior of the library is consistent: it doesn't know the idea of `signal` yet at least it's not handled in any special way.

I expected that `signal` will be passed to `Request` constructor and so it will be consumed by `WindowOrWorkerGlobalScope.fetch`. That's at least what the spec suggests: https://fetch.spec.whatwg.org/#requestinit - `RequestInit` dictionary has optional key `signal`.

`signal` given to the `RequestInit` of fetch-client's `fetch` is in fact passed to the `Request` constructor, but it has no effect whatsoever.

The behavior of browsers is not consistent:

Firefox has a `signal` property on the instance of `Request` but it's not the `signal` that was passed to `Request` constructor in the `init` param. It's a different one.

If `signal` is passed to `WindowOrWorkerGlobalScope.fetch` 2nd argument then request gets aborted as expected.

Chrome 66 (Canary) does not have `signal` property on the `Request` instance at all. 

Edge 16 behaves more or less like Firefox.

* **What is the motivation / use case for changing the behavior?**

Implementing fetch abort in a usable way will allow aborting fetch requests which means fetch can be used in places where the only choice was XHR (my use case: server-side autocomplete)

---

I applied a patch to a compiled version of fetch-client changing 

https://github.com/aurelia/fetch-client/blob/07d719665f350843b734a4456d8cef211c4f6a4b/dist/commonjs/aurelia-fetch-client.js#L135

to:

```js
if (init.signal && init.signal instanceof AbortSignal) {
  response = fetch(result, {
    signal: init.signal,
  });
} else {
  response = fetch(result);
}
```

An it works in Firefox and Edge. It doesn't work in Chrome 66 (Canary)

I'd like to put such change under discussion - Edge and Firefox have `AbortSignal` in stable releases and default behavior of fetch-client doesn't seem to support it.

**Comment by Alexander-Taran** [comment]
Would you like to come up with a pull request for that?
What would be the fallback strategy for the browsers that do not support it?
Is it implemented in the whatwg-fetch polifil?

**Comment by doktordirk** [comment]
@Alexander-Taran As the signal is just one entry of the Request(Init), it works already actually. see PR
