### ISSUE TITLE
unable to modify request header using an interceptor

### ISSUE THREAD

**Issue by arnonuem** [aurelia/fetch-client#107]
When intercepting a request it seems to be impossible to modify request headers.

```
   http.configure( config => {
      config
            .withBaseUrl( cfg.gas2goSalesBaseUrl )
            .withDefaults( {
              headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
              }
            })
            .withInterceptor( this.tokenInterceptor );
    } );
```

```
  get tokenInterceptor() {
    let me = this;
    return {
      request( request ) {
        console.log( JSON.stringify( request) );   // logs {} - but why?

        let token = AureliaCookie.get( 'jwt.token' );
        let expiresAt = AureliaCookie.get( 'jwt.token.expires' );

        if ( me.isTokenValid( token, expiresAt ) ) {
          request.headers.append( 'Authorization', 'Bearer ' + token );

          // console.log( 'Intercepting request...' );
          // console.log( 'Adding Bearer Token' );
          // request.headers.Authorization = 'Bearer ' + AureliaCookie.get( 'jwt.token' );
          console.log(`Requesting ${request.method} ${request.url}`); //logs a valid url
          console.log(`Headers ${JSON.stringify(request.headers)}`);  //logs {} but why?
        }
        return request;
      }
    };
  }
```

In the debugger i see that the line 'request.headers.append' is executed but somehow the request object does not contain any headers which can be modified. The request object ist just '{}' but why?

Finally i dont see my Authorization header in chrome dev tools :(

**Comment by doktordirk** [comment]
not that it should make a difference, but i use headers.set instead of append

**Comment by arnonuem** [comment]
> not that it should make a difference, but i use headers.set instead of append

When using `fetch-client` it is `headers.append` and when using `http-client` it is `headers.add` but the problem here is that it seems like modification to the headers object which are done in an interceptor are ignored somehow.
Also it is strange that when i log the headers object with `JSON.stringify` then i see `{}` but when i log `headers.url` i see a url. This behaviour for me is a bit mystical.
Nevertheless i have not managed it to manipulate the request headers within an interception of the request. I know that in Angular it is no problem to do so :(
I just want to add `Authorization: 'Bearer rz87rzr8z3...'` to my headers.

**Comment by arnonuem** [comment]
I just tested `headers.set` with no success.

**Comment by arnonuem** [comment]
@Alexander-Taran i already did and found no symmantic difference there.

**Comment by davismj** [comment]
> Also it is strange that when i log the headers object with JSON.stringify then i see {} but when i log headers.url i see a url. This behaviour for me is a bit mystical.

This is just how the Request object works in Chrome and maybe other problems. It functions as a Map. `JSON.stringify(new Map(['foo','bar']))` yields `{}` as well. If you want to log it, use `JSON.stringify(Array.from(a.headers))`.

https://developer.mozilla.org/en-US/docs/Web/API/Headers

**Comment by arnonuem** [comment]
It seems that `request.headers.set( 'Authorization', 'Bearer ' + token );` seems to work. So i am closing this for now. Many thanks to @doktordirk and @davismj
