### ISSUE TITLE
Cannot find name 'AbortSignal'

### ISSUE THREAD

**Issue by PeterWone** [aurelia/fetch-client#111]
**I'm submitting a bug report**
* **Library Version:**
1.4.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 2.6.1

* **Browser:**
Chrome 69.0.3497.81 (Official Build) (64-bit) (cohort: 69_win_81), Edge 11
* **Language:**
TypeScript X.X

**Current behavior:**
node_modules\aurelia-fetch-client\dist\aurelia-fetch-client.d.ts
(111,12): error TS2304: Cannot find name 'AbortSignal'.

1.3.1 works fine. If the problem is that 1.4.0 requires other updates then it would be handy to list them.

* **What is the expected behavior?**
Not barfing

* **What is the motivation / use case for changing the behavior?**
Barfing is bad

**Comment by davismj** [comment]
@fkleuver So we should update this line?

`"typescript": "^1.9.0-dev.20160622-1.0",`

https://github.com/aurelia/fetch-client/blob/master/package.json#L88

**Comment by fkleuver** [comment]
@davismj Wow, 1.9.0-dev. Yeah, that ought to be updated..

**Comment by davismj** [comment]
I'm not sure how to solve this. Updating the dev dependency won't fix OPs issue. Adding a peer dependency ^2.7 might, but then will raise annoying warnings to non TypeScript users. Perhaps we add console output on install?

**Comment by PeterWone** [comment]
I only logged the issue as a courtesy. Just put it in the release notes if it's a huge PITA to fix. All you need to say is either update TS or use 1.3.1 if you can't update TS for some reason.
