### ISSUE TITLE
Converting repo to typescript

### ISSUE THREAD

**Issue by dannyBies** [aurelia/fetch-client#112]
Hey guys,

I wanted to get some more experience in converting existing javascript repositories to typescript. So I chose this repo [to try it out](https://github.com/dannyBies/fetch-client). so far I've done the following things:

- Convert every .js file to .ts
- Remove dependencies on babel and gulp / general cleanup of packages
- Refactor code

It is not finished yet but I was wondering if there is any interest in doing this? If there is I'll clean up my code and get it ready, otherwise I'll keep it as is.

**Comment by EisenbergEffect** [comment]
Hey @dannyBies !

We're definitely interested in this! Our vNext Aurelia is fully TypeScript and we're investigating which of our vCurrent modules should move over to vNext. The first step in that is doing some TypeScript conversions. I think we'd love to have a vNext fetch client available out of the box, so it certainly makes sense to start with moving our vCurrent version to TypeScript. If you'd like to continue working on this, we'd be happy to accept a PR.

I haven't dug deeply into your setup in the linked repo. One of the important things will be to try to have the same sort of build setup as other vCurrent TS libraries, such as the new i18n TS branch, the dialog plugin or validation. Having the same setup makes it easier for us to publish consistently and also paves the way for more easily moving to our vNext monorepo.

If this all sounds good, please proceed with this conversion work and if you enjoy that, I think we can find more opportunities for you to help out in this and other ways related to TypeScript as well. Thanks!

**Comment by dannyBies** [comment]
@EisenbergEffect Sounds good to me! I'll keep working on it and when it's ready for review I'll open a PR.

I have based most of the setup on the i18n TS branch as I thought it would be most up to date to the standards, luckily I made the right assumption :)

**Comment by EisenbergEffect** [comment]
Awesome! Looking for to seeing the PR. While you are working on that, if you can, keep an eye on the other issues on this repo in case some other fixes are made during the conversion work. There's an issue right now related to AbortSignal types in particular to keep an eye on. I think it's just a config issues and probably even fixed in your branch. But, just in case, we want to be careful we don't introduce regressions during the port.

**Comment by dannyBies** [comment]
Yeah I'll make sure I implement any fixes that occurred after I branched off. The AbortSignal issue should be fixed in my branch but I'll make sure to test it after I have a stable branch.

**Comment by EisenbergEffect** [comment]
TS version merged in.
