### ISSUE TITLE
HTTP methods must be upper case

### ISSUE THREAD

**Issue by Tim-Erwin** [aurelia/fetch-client#117]
**I'm submitting a bug report**

* **Library Version:**
1.7.0

* **Browser:**
Chrome and Firefox, probably all

* **Language:**
TypeScript 3.1.2, probably all

**Current behavior:**
CORS request fails for all methods but GET.

**Expected/desired behavior:**
CORS should work for all methods.

As per [RFC-7230](https://tools.ietf.org/html/rfc7230#section-3.1.1) methods are case-sensitive and must be upper case. However, the fetch client uses lower case method names except for GET (where it doesn't specify the method name, so it falls back to the default which is of course upper case). This leads to CORS requests with lower case method names which then don't match the upper case response, ergo the access is denied.

**Comment by bigopon** [comment]
@Tim-Erwin nice find, would be awesome if you could PR to fix it 😄

**Comment by Tim-Erwin** [comment]
Already on it :)
