### ISSUE TITLE
Version 1.8.1 "cannot find module 'aurelia-fetch-client'"

### ISSUE THREAD

**Issue by ndench** [aurelia/fetch-client#129]
**I'm submitting a bug report**

* **Library Version:**
1.8.1

**Please tell us about your environment:**
* **Operating System:**
Linux (ubuntu 16.04)

* **Node Version:**
8.15.0

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
webpack 3.2.3

* **Browser:**
all

* **Language:**
TypeScript 3.1

**Current behavior:**
Running webpack build results in an error
> TS2307: Cannot find module 'aurelia-fetch-client' 

For every file that imports the fetch client.

Steps to reproduce:
- Install version 1.8.1
- Run webpack
- Observe error
- Install version 1.8.0
- Run webpack
- Build completes successfully

**Comment by fkleuver** [comment]
Yep, something went wrong with the last release. Dist files are completely missing. Thanks for reporting! We're on it

**Comment by fkleuver** [comment]
@ndench It should be fixed now with 1.8.2. Could you please verify? Thanks!

**Comment by ndench** [comment]
@fkleuver yep, that works for me. Thanks for the speedy fix! It was jump dumb luck that I ran an upgrade 5 minutes after you released 1.8.1 :joy:
