### ISSUE TITLE
Setting default headers with TypeScript

### ISSUE THREAD

**Issue by Souldrinker** [aurelia/fetch-client#16]
When I switched from the http client to the fetch client I had some issues setting default headers in main.ts using TypeScript to make things work in Firefox (which seem to default to xml rather than json) equivalent to this:

```
aurelia.container.registerInstance(HttpClient, new HttpClient().configure(builder => builder.withHeader("Accept": "application/json", "Content-Type": "application/json")))
```

When setting headers using RequestInit as a second parameter to fetch it worked just fine like: 
```
        const headers = new Headers();
        headers.append("Accept", "application/json");
        headers.append("Content-Type", "application/json");
        this.http.fetch("api/mymethod", {
                method: "post",
                headers: headers,
                body: JSON.stringify(data)
            });
```

But when I tried it similar in the configure method:
```
const headers = new Headers();
    headers.append("Accept", "application/json");
    headers.append("Content-Type", "application/json");
    aurelia.container.registerInstance(HttpClient, new HttpClient().configure(builder => builder.withDefaults({headers: headers})));
```
I got errors telling me that ```Default headers must be a plain object.```.

After trying some different approaches I got a tip in the gitter chat that I should do like this:
```
aurelia.container.registerInstance(HttpClient, new HttpClient().configure(builder => builder.withDefaults({ headers: { "Accept": "application/json", "Content-Type": "application/json"}})));
```
But since headers in RequestInit expects a Headers object which isn't a plain object I got stuck until I changed ```headers?: Headers``` to ```headers?: Headers | Object``` for RequestInit in aurelia-fetch-client.d.ts.

So now all is fine for me, but I suppose there is some fixing needing to be done here. I suppose you either should change the type of headers in RequestInit to allow plain objects or allow a Headers object to be passed in to the header property or however you want to solve it?

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you address this?

**Comment by Cali03** [comment]
Hi,

Seems to be that the problem is not fixed :

Uncaught Error: Default headers must be a plain object.configure 
@ aurelia-fetch-client.js:96settings.submit 
@ settings.ts:111evaluate 
@ aurelia-binding.js:1396callSource 
@ aurelia-binding.js:4801(anonymous function) 
@ aurelia-binding.js:4826handleDelegatedEvent 
@ aurelia-binding.js:2966

**Comment by joshSummerhays** [comment]
Seems for me as well that this is not fixed. 
"typescript": "~2.4.2"
angular 5

ERROR in src/app/services/http.service.ts(56,29): error TS2345: Argument of type '{ method: string; headers: { 'Content-Type': string; }; body: string; }' is not assignable to parameter of type 'RequestInit'.
  Types of property 'headers' are incompatible.
    Type '{ 'Content-Type': string; }' is not assignable to type 'Headers | string[][]'.
      Object literal may only specify known properties, and ''Content-Type'' does not exist in type 'Headers | string[][]'.

**Comment by w9jds** [comment]
Yeah, this doesn't work for me either. If I move it all to arrays like the error suggests it doesn't send them at all, and creating a header object and appending them also doesn't change anything.

**Comment by stevematdavies** [comment]
Same issue as @w9jds
