### ISSUE TITLE
Allow functions to be set as default headers

### ISSUE THREAD

**Issue by lukechilds** [aurelia/fetch-client#17]
I'm currently writing a simple api client on top of the fetch client. The api requires a JWT header for authentication and using `.withDefaults()` is a really nice way of doing this:

```
constructor(http, auth) {

  this.auth = auth;
  this.client = http
    .configure(config => {
      config
        .withDefaults({
          headers: {
            'Authorization': `Bearer ${this.auth.getToken()}`
          }
        });
    });

}
```

The only issue with this is that my JWTs expire/renew every hour so the default `Authorization` header string will expire. Users have to refresh the page to get the api client to use the new token.

You can easily work around this by wrapping fetch with your own method that manually sets the token header for each request, however this isn't quite as seamless as using `.withDefaults()`.

I think it would be really neat if the default headers object allowed the header values to be set as a function to be evaluated on each request. I have a modified version of `fetch-client` that allows the following usage:

```
constructor(http, auth) {

  this.auth = auth;
  this.client = http
    .configure(config => {
      config
        .withDefaults({
          headers: {
            'Authorization': () => `Bearer ${this.auth.getToken()}`
          }
        });
    });

}
```
Unless I've missed something obvious it seems like this could be a common problem people might have. Is this something you'd be interested in accepting a pull request for?

**Comment by bryanrsmith** [comment]
Certainly! This can be accomplished now with a request interceptor, but
this change would greatly simplify this use case.

**Comment by lukechilds** [comment]
Sweet.

Right, I've got something together. I've read through your contributing guidelines but I'm a little confused as to whether I should `gulp build` and commit `dist`, or just commit `src` and `test`.

**Comment by EisenbergEffect** [comment]
Avoid comiting the dist please :)
