### ISSUE TITLE
Typescript and Interceptors

### ISSUE THREAD

**Issue by Ullfis** [aurelia/fetch-client#19]
Thank you for your excellent work on Aurelia and all her components.

After testing typescript and fetch-client I believe the definition file need a tiny change.

This wont compile (from https://gist.github.com/bryanrsmith/14caed2015b9c54e70c3):
```javascript
httpClient.configure(config => {
    config
        .withBaseUrl('api/')
        .withDefaults({
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'X-Requested-With': 'Fetch'
            }
        })
        .withInterceptor({
            request(request) {
                console.log(`Requesting ${request.method} ${request.url}`);
                return request; // you can return a modified Request, or you can short-circuit the request by returning a Response
            },
            response(response) {
                console.log(`Received ${response.status} ${response.url}`);
                return response; // you can return a modified Response
            }
        });
});
```

From aurelia-fetch-client.d.ts:

```javascript
79. withInterceptor(interceptor: Interceptor): HttpClientConfiguration;
```

and

```javascript
4. /* eslint-disable */
export interface Interceptor {
  request(request: Request): Request | Response | Promise<Request | Response>;
  requestError(error: any): Request | Response | Promise<Request | Response>;
  response(response: Response): Response | Promise<Response>;
  responseError(error: any): Response | Promise<Response>;
}
```

I have not read the source (yet) but I don't think its necessary to define all Interceptors. Compiling/running project with suggested change work.

Change suggestion (add '?'):

```javascript
4. /* eslint-disable */
export interface Interceptor {
  request?(request: Request): Request | Response | Promise<Request | Response>;
  requestError?(error: any): Request | Response | Promise<Request | Response>;
  response?(response: Response): Response | Promise<Response>;
  responseError?(error: any): Response | Promise<Response>;
}
```

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you look into this?

**Comment by bryanrsmith** [comment]
Yes, they are all optional, and appear to be marked that way in source: https://github.com/aurelia/fetch-client/blob/master/src/interfaces.js#L15

@cmichaelgraham Is there maybe something wrong with the syntax I'm using, or a bug in the generator?

**Comment by cmichaelgraham** [comment]
didn't know you could have an optional method defined like that.

i found this on [stackoverflow](http://stackoverflow.com/questions/27522973/typescript-optional-function-in-interface)

There are currently three syntaxes TypeScript allows for function declarations in interfaces:

Using your example of a validation function taking 1 parameter (of any type) and a boolean return value:

```javascript
validation: {(flag: any): boolean};
```

or in the newer syntax:

```javascript
validation(flag: any) : boolean;
```

or an alternative is:

```javascript
validation: (flag: any) => boolean;
```

## Solution:

so to make it optional with the old syntax is easy:

```javascript
validation?: {(flag: any): boolean};
```

with the second syntax (recent addition - thanks to @toothbrush)

```javascript
validation?(flag: any) : boolean;
```

or in the third syntax (as you found):

```javascript
validation?: (flag: any) => boolean;
```

**Comment by cmichaelgraham** [comment]
hmmmm... i'm a bit puzzled...  babel doesn't like this syntax - it complains about the `(`, saying it is an unexpected character:

```
interface IFoo {
  foo?(bar: number): void;
}
```

while it seems fine with this:

```
interface IFoo {
  foo?: (bar: number) => void;
}

NOTE: `babel-dts-generator` is suppressing the `?` still, but i can fix that.  i'll start working on the fix, but is the esteemed @bryanrsmith willing to use the second syntax?

ping @EisenbergEffect

**Comment by bryanrsmith** [comment]
I'll use whatever syntax works :-)

**Comment by cmichaelgraham** [comment]
cool - i'm on it :+1: - already have a failing test...

**Comment by bryanrsmith** [comment]
As far as I can tell this has been resolved. Please reopen if that's not correct.
