### ISSUE TITLE
'Headers' is undefined

### ISSUE THREAD

**Issue by out-of-memory** [aurelia/fetch-client#20]
I am getting following error only in IE

SCRIPT5009: 'Headers' is undefined
File: aurelia-fetch-client.js, Line: 90, Column: 7

this is the line in aurelia-fetch-client.js , where i am getting the error:
 if (defaults && defaults.headers instaehnceof Headers) {

Any solution, or i am doing something wrong...
I am using Typescript as my language to code. I have also looked into the d.ts file its also right.

**Comment by EisenbergEffect** [comment]
You will need to include the fetch polyfill.
