### ISSUE TITLE
Dependency on github/fetch?

### ISSUE THREAD

**Issue by steamonimo** [aurelia/fetch-client#21]
I added the fetch-client to my project and somehow the dependency to the project github/fetch was not resolved. I added it manually with "jspm install fetch" and the fetching as you demonstrate here started to work again: https://github.com/aurelia/skeleton-navigation/blob/master/src/users.js

**Comment by EisenbergEffect** [comment]
@bryanrsmith Have we determined how we want to handle this?

**Comment by bryanrsmith** [comment]
Yes. I added this to the docs (which I realize are not super easy to find right now): https://github.com/aurelia/fetch-client/tree/master/doc#bring-your-own-polyfill

I could also modify the code to check if fetch is available, and throw a more helpful error.

**Comment by EisenbergEffect** [comment]
I think the helpful error is a good idea.
Speaking of docs, is there any way you would be able to write some docs on fetch and the router for next week's release? For the router, you can take what we have today, and just flesh it out a bit more. We would need it ready to go by Monday so I have time to incorporate it. Let me know.
