### ISSUE TITLE
Typescript issue (beta1)

### ISSUE THREAD

**Issue by vip32** [aurelia/fetch-client#23]
when using aurelia-fetch-client as a jspm package the aurelia-fetch-client.d.ts causes the following errors on build:

```
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(18,25): error TS2304: Cannot find name 'Request'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(18,37): error TS2304: Cannot find name 'Request'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(18,47): error TS2304: Cannot find name 'Response'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(18,66): error TS2304: Cannot find name 'Request'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(18,76): error TS2304: Cannot find name 'Response'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(27,36): error TS2304: Cannot find name 'Request'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(27,46): error TS2304: Cannot find name 'Response'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(27,65): error TS2304: Cannot find name 'Request'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(27,75): error TS2304: Cannot find name 'Response'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(35,27): error TS2304: Cannot find name 'Response'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(35,40): error TS2304: Cannot find name 'Response'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(35,59): error TS2304: Cannot find name 'Response'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(45,37): error TS2304: Cannot find name 'Response'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(45,56): error TS2304: Cannot find name 'Response'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(54,15): error TS2304: Cannot find name 'Headers'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(55,19): error TS2304: Cannot find name 'BufferSource'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(55,45): error TS2304: Cannot find name 'URLSearchParams'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(201,18): error TS2304: Cannot find name 'Request'.
jspm_packages\npm\aurelia-fetch-client@1.0.0-beta.1\aurelia-fetch-client.d.ts(201,65): error TS2304: Cannot find name 'Response'.
```

can be related to https://github.com/aurelia/fetch-client/issues/19

**Comment by bryanrsmith** [comment]
@vip32 The missing types are part of the new Fetch API (a new DOM API), which are not yet supported by the DOM definitions included with TS. The types are included in `doc/whatwg-fetch.d.ts` in this repo. I've made a change to the build so that those types will be included in the .d.ts for this library. The change will go out with the next release, probably in a few days.

**Comment by andrevlins** [comment]
I'm getting this error with aurelia cli build command using typescript. 

There are any workaround?

**Comment by EisenbergEffect** [comment]
I think we've tracked down the issue with this. Try replacing your transpile task with this one: https://github.com/aurelia/cli/blob/master/lib/resources/tasks/transpile.ts  You will also have to npm install `event-stream`. Let me know if that fixes the problem for you.

**Comment by andrevlins** [comment]
I'll try, thank you

**Comment by kuechlerm** [comment]
Changing transpile.ts did not help. I get the same error.

**Comment by kuechlerm** [comment]
Some observations: 
I use the aurelia-cli v0.16.1. 
If I use the fetch-client, I get the Typescript errors mentioned by @vip32. 
With whatwg-fetch.d.ts via typings and url.d.ts as a custom typing `au build` works. 
If I use `au run --watch`, the first build works, but most subsequent builds have the same errors. 
Using the new transpile.ts provided by @EisenbergEffect 3 comments up solves the issue for me.

**Comment by vbnewb** [comment]
@kuechlerm 
This is what worked for me.

Get a copy of whatwg-fetch.d.ts and put it in your custom_typings folder.

Preferably : https://github.com/cmichaelgraham/aurelia-typescript/blob/master/skel-nav-atom/whatwg-fetch/whatwg-fetch.d.ts

His copy has an interface for BufferSource which was not in another definition file I found.
