### ISSUE TITLE
Fetch Helpers for Common Tasks

### ISSUE THREAD

**Issue by bchavez** [aurelia/fetch-client#26]
I've been upgrading from **pre-beta** to **beta1**, I was a bit upset migrating `aurelia-http-client` to the new `aurelia-fetch-client` primarily because I feel the raw **fetch API** a step backwards from the simplicity we got to know in the original `aurelia-http-client`.

For example, take a look at how much setup is required to fire-off a JSON `POST`:

```
this.http.fetch(`${baseUrl}/ExternalLogins`, {
    method: "POST",
    headers: {
        "Content-Type": "application/json; charset=utf-8"
    },
    body: JSON.stringify({
        returnUrl: "/app",
        generateState: false
    })
})
```
1. Explicitly define the `method: POST`
2. Explicitly define the `Content-Type`
3. Explicitly jsonify the `body` paypload.

Now, compare this to `aurelia-http-client`:

```
this.http
  .createRequest(`${baseUrl}/ExternalLogins`)
  .asGet()
  .withParams({ returnUrl: "/app", generateState: false })
  .send();
```

I ***really*** think we need some helpers to help common use cases like `POST`ing JSON. Something that helps set content-type, method, and auto-body json encoding if it encounters a POJO.

**Comment by bryanrsmith** [comment]
There is a helper function called `json` that does exactly that. https://github.com/aurelia/fetch-client/tree/master/doc#helpers

```js
import { HttpClient, json } from 'aurelia-fetch-client';
...
this.http.fetch(`${baseUrl}/ExternalLogins`, {
    method: "POST",
    body: json({ returnUrl: "/app", generateState: false })
})
```

**Comment by bchavez** [comment]
Ah, thank you; that does alleviate most of the issues.
