### ISSUE TITLE
Successful POST request's promise is rejected

### ISSUE THREAD

**Issue by alexpyoung** [aurelia/fetch-client#29]
Hi, apologies for such a trivial problem but I'm really scratching my head here.

In my view model I configure the fetch client (example is attempting Github OAuth) like so:
```js
constructor(
    http
) {

    http.configure(config => {

        config
            .useStandardConfiguration()
            .withBaseUrl('https://github.com/')
            .withDefaults({
                mode: 'no-cors',
                headers: {
                    'Accept': 'application/json'
                }
            });
    });

    this.http = http;
}
``` 
[After successfully authorizing the client and receiving an verification code, I request an access token:](https://developer.github.com/v3/oauth/#2-github-redirects-back-to-your-site)
```js
requestAccessToken() {

    let url = 'login/oauth/access_token';
    url += `?client_id=${ this.client_id }`;
    url += `&client_secret=${ this.client_secret }`;
    url += `&code=${ this.oauth_code }`;

    return this.http.fetch(url, {
        method: 'POST',
    });
}
```
The request returns a 200 status with the appropriate body, however the `Promise` returned is always rejected and I am unable to access the response. i.e.
```js
requestAccessToken()
    .then(
        response => {
            // Never invoked
        },
        error => {
            // Always invoked
        }
    );

**Comment by bryanrsmith** [comment]
What's the error that it rejects with? What do you see in the console? Without more information I can only guess, but I suspect it's because you're using `mode: 'no-cors'` on a cross-origin request. Do you get a different result if you change it back to the default of `'cors'`?

**Comment by bryanrsmith** [comment]
Feel free to reopen this if there's more I can do to help.

**Comment by alexpyoung** [comment]
@bryanrsmith the error response looks like so:

![screen shot 2015-12-14 at 8 28 36 pm](https://cloud.githubusercontent.com/assets/2624187/11799348/48154e6a-a2a1-11e5-973e-a797952d1513.png)

Is it possible to make CORS requests with the fetch client then if I exclude `mode: 'no-cors'`? Alternatively, I might try JSONP with the HTTP client.

**Comment by alexpyoung** [comment]
Whoops. Trying to `POST` with `JSONP` is no fun. But it looks like you were looking in the right direction @bryanrsmith. Without `mode: 'no-cors'`:
```
Fetch API cannot load https://github.com/login/oauth/access_token...
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:9000' is therefore not allowed access. 
If an opaque response serves your needs, 
set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
[Github indicates it supports CORS](https://developer.github.com/v3/#cross-origin-resource-sharing) so I wonder what's going on. Is this an issue with the fetch-client?

**Comment by bryanrsmith** [comment]
The `type: "opaque"` in the response means that you cannot read the response from javascript. This is why you're seeing the rejection, and it is expected from `no-cors` requests. You can read about this on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode). As you can see from the second error message, GitHub is not attaching CORS headers to the response. I googled the URI you're requesting and found this: https://github.com/isaacs/github/issues/330.

Hope this helps.

**Comment by alexpyoung** [comment]
It looks like this might be a dead-end for my current implementation, as my `client_secret` is indeed exposed on my demo app. Appreciate the lead.

**Comment by KOueslati** [comment]
You can set a no-cors mode like the code below

var myHeaders = new Headers();
var myInit = { method: 'POST',
               headers: myHeaders,
               mode: 'no-cors',
               cache: 'default' };

return this.http.fetch(url, myInit);
