### ISSUE TITLE
Make request available in Interceptor.response/responseError

### ISSUE THREAD

**Issue by timbell** [aurelia/fetch-client#33]
Could the Interceptor.response and (especially) responseError methods be extended to include the original request? This would allow us to implement 401 handling with retry as can be done with http-client using HttpResponseMessage.requestMessage.

**Comment by bryanrsmith** [comment]
Yes, good idea!

**Comment by bryanrsmith** [comment]
I'll try to work on this soon, but in the meantime it would be a good feature for someone interested in contributing! Here's what it would probably take:

1. Modify [`applyInterceptors`](https://github.com/aurelia/fetch-client/blob/master/src/http-client.js#L198) to accept an optional array of additional arguments to the interceptors. Need to change the interceptor invocation to something like `successHandler && x => interceptor.successHandler(x, ...interceptorArgs)`.
1. Modify [`processResponse`](https://github.com/aurelia/fetch-client/blob/master/src/http-client.js#L194)'s parameter list to accept the response and pass it along to `applyInterceptors`.
1. Include `result` in the arguments [passed to `processResponse` ](https://github.com/aurelia/fetch-client/blob/master/src/http-client.js#L113)
1. Add a test or two to cover the new functionality.

**Comment by timbell** [comment]
I can have a shot at this sometime this week if you like?

Date: Sun, 17 Jan 2016 12:00:26 -0800

**Comment by timbell** [comment]
I have prepared a branch with the changes but I don't have the rights to publish to the repository (I have just submitted the a CLA).

**Comment by EisenbergEffect** [comment]
@bryanrsmith  CLA is confirmed.
@timbell You should be able to create a pull request from your branch on GitHub. Then we can review it and merge.

**Comment by timbell** [comment]
Struggling to push local changes =>

git push origin include-original-request-in-interceptor-response-callbacks
remote: Permission to aurelia/fetch-client.git denied to timbell.
fatal: unable to access 'https://github.com/aurelia/fetch-client.git/': The requested URL returned error: 403

**Comment by Gheoan** [comment]
You have to first fork this repo.
Then add the fork as a remote.
`git remote add fork https://github.com/timbell/fetch-client.git`
Then `git push fork include-original-request-in-interceptor-response-callbacks`. Now you should see the 'submit pull request' button on https://github.com/timbell/fetch-client

**Comment by timbell** [comment]
@Gheoan - thanks. I've managed to submit something now - hopefully not too wrong...

**Comment by timbell** [comment]
@bryanrsmith - sorry, I presume my commit comment closed this?
I've updated the pull request

**Comment by stevies** [comment]
I assume a similar change was not made to aurelia/http-client?  Are there plans for adding this?
