### ISSUE TITLE
 Null body status (204) is not handled correctly

### ISSUE THREAD

**Issue by cdennig** [aurelia/fetch-client#36]
Hi there,

it seems that the aurelia fetch client doesn't handle "null body statuses" (in my case "204") in a proper way. E.g., if I call my api (PUT request, response is "Status Code": 204 with body = null):

    httpClient.fetch(requestUri, reqInit) // method: PUT
            .then(response => {
             // never called
             }
            .catch((err) => {
                console.error(err); // --> SyntaxError: Unexpected end of input {message: "Unexpected end of input"}
            });

In the reponse, the body is null. So I guess that is the problem.

To check the handling, I switched the status code for testing purposes to "200" with content set in the body. Everything works fine with that configuration.

Please have a look at the issue.

Many thanks,
Chris

**Comment by bryanrsmith** [comment]
I should be able to look into this tonight. As far as I know this library never tries to read the response body, though. Do you have any response interceptors registered?

**Comment by bryanrsmith** [comment]
@cdennig I haven't been able to reproduce this. A PUT responding with a 204 is working as expected for me. Can you provide a more complete code sample? I suspect there's a response interceptor that's trying to read the response body.

**Comment by cdennig** [comment]
Ahh...sorry. In my code, I also did a "response.json()". So here is the full example:

    httpClient.fetch(requestUri, reqInit) // method: PUT
        .then(response => {
             response.json().then((message) => {
                        if (response.status === 204) {
                            success(message, response);
                        } else {
                            error(message);
                        }
                    });
         }
        .catch((err) => {
            console.error(err); 
        });

Sorry for the inconvenience, the error comes from calling "json()". If I add the catch block to response.json() everything works fine.

(But: maybe invoking .json() with a null-body-response should just return "null" to the caller?!)

Regards,
Chris

**Comment by bryanrsmith** [comment]
Cool, no problem. `Response` is part of the browser's fetch API, so in order to handle this we'd have to abstract that interface. We're hoping to avoid that since it would make this library a lot heavier.
