### ISSUE TITLE
Relative URI in HTTPS reverts to HTTP

### ISSUE THREAD

**Issue by steamonimo** [aurelia/fetch-client#42]
I am loading my Aurelia App via HTTPS. In my App I will load a resource from a location two folders above the App location. Thus I use a relative URI with "../../". If I load the App via HTTP this works perfectly. But in HTTPS this relative fetch does revert to HTTP instead of HTTPS. As a result I will get the mixed content warning and the fetch-client will block the download.

	this.http.fetch("../../folder/xy", {
		method: 'get',
		dataType: 'xml'
	})

Excepted behaviour: use the location of the App to identify the correct connection type for relative URI (HTTP, HTTPS).

**Comment by bryanrsmith** [comment]
This seems to work fine for me. Can you provide a complete repro?

**Comment by steamonimo** [comment]
My App is located at "https://www.domain.com/app/xy/" and the static file I would like to load is "https://www.domain.com/folder/file.xy". Thus the relative path of the file is "../../folder/file.xy"

	this.http.fetch("../../folder/file.xy", {
		method: 'get',
		dataType: 'xml'
	})
			.then(response => response.text())
			.then(response => {
				var xmlDoc = jQuery.parseXML(response);
				if (xmlDoc) {
					var nodes = xmlDoc.childNodes[0];
					...
				}				

			}).catch(err => {
				console.log("Error: " + err);
			});
However in HTTPS this relative fetch reverts to HTTP.

**Comment by steamonimo** [comment]
I found my mistake. In my http configuration I initialized http with a fixed base url using .withBaseUrl("http://...)

This caused the connection to revert to HTTPS for the relative URL.

Sorry for my misinterpretation.
