### ISSUE TITLE
Mock implementation for unit testing

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/fetch-client#44]
One thing I found very helpful in Angular 1 was the [`$httpBackend` ](https://docs.angularjs.org/api/ngMock/service/$httpBackend) service. This provides a fake HTTP backend to verify requests made by the unit under test. If, for instance, the code to test does this:
```js
// The controller code
function MyController($scope, $http) {
  var authToken;

  $http.get('/auth.py').then(function(response) {
    authToken = response.headers('A-Token');
    $scope.user = response.data;
  });
}
```

then the test could be:
```js
// testing controller
describe('MyController', function() {
   beforeEach(inject(function($httpBackend) {
     ...
     authRequestHandler = $httpBackend.when('GET', '/auth.py')
                            .respond({userId: 'userX'}, {'A-Token': 'xxx'});
   }));

   afterEach(function() {
     $httpBackend.verifyNoOutstandingExpectation();
     $httpBackend.verifyNoOutstandingRequest();
   });

   it('should fetch authentication token', function() {
     $httpBackend.expectGET('/auth.py');
     var controller = createController();
     $httpBackend.flush();
   });
});
```

It would be very helpful to have something similar for the fetch-client.

**Comment by bryanrsmith** [comment]
Thanks for the suggestion, but I don't think we'd gain anything by adding an API for this. For unit tests I would recommend mocking `HttpClient`. If you want to run `HttpClient` code in your test then you can either mock `window.fetch`, or add a request interceptor that returns a `Response`, which will bypass the call to `window.fetch`.

**Comment by RomkeVdMeulen** [comment]
It's not just the mocking itself, it's the administration of (un)met expectancies. I think this is a pretty common concern for projects that make requests to a backend. It would be nice to have it in this project, so people don't have to re-invent the wheel.

On the other hand, if you hook into window.fetch, you can do the same without relying on the HttpClient API. So perhaps this belongs in the testing framework itself, or a plugin, or a separate project.

Thanks for your time.
