### ISSUE TITLE
Massive delay in fetching json files in Microsoft Edge

### ISSUE THREAD

**Issue by avizcaino-newuibcn** [aurelia/fetch-client#45]
Hi,

I'm having trouble with downloading json files with aurelia-fetch-client. I'm having a really big delay between when retrieving these files as shown below:

![image](https://cloud.githubusercontent.com/assets/9590299/14287403/d93eec02-fb52-11e5-8dc6-0e7a438ebf4f.png)

This only happens in Microsoft Edge. Chrome is working well.
I've tried with xmlhttprequest too and having the same problem. I couldn't find the problem...

**Comment by bryanrsmith** [comment]
> I've tried with xmlhttprequest too and having the same problem

Then your problem is unrelated to this library. Is there something specific I can do to help you? The screenshot makes it look like the server is the source of the delay.

**Comment by alvarezmario** [comment]
@avizcaino-newuibcn this is due to Edge's Promise implementation, is a known issue and out of Aurelia's control. This being said, there is a fix, you'll need to add Bluebird promise library and it'll work just fine. See this link: https://www.danyow.net/edge-promise-perf/

**Comment by alvarezmario** [comment]
@avizcaino-newuibcn this is due to Edge's Promise implementation, is a known issue and out of Aurelia's control. This being said, there is a fix, you'll need to add Bluebird promise library and it'll work just fine. See this link: https://www.danyow.net/edge-promise-perf/

**Comment by alvarezmario** [comment]
@avizcaino-newuibcn check this blog too: http://blog.durandal.io/2015/12/17/more-aurelia-performance-bug-fixes-docs-and-typescript-awesome/

**Comment by bryanrsmith** [comment]
@alvarezmario Maybe, but the screenshot shows the initial HTML document with the same delay, which makes me think the issue is with the server.

**Comment by avizcaino-newuibcn** [comment]
@alvarezmario Already using Bluebird :(
