### ISSUE TITLE
request without body property in responseError interceptor

### ISSUE THREAD

**Issue by dilvish4ever** [aurelia/fetch-client#46]
`body` property is lost in `request` parameter when responseError interceptor fires. 
`bodyUsed` property is true - in case of POST, PUT etc request. Request resending is impossible.
```typescript
.withInterceptor({
 responseError: (response, request) => {
                        switch (response.status) {
                            case 401:
                                return Container.instance.get(Login).login()
                                .then(()=>this.httpClient.fetch(request));
////////////////
```

**Comment by bryanrsmith** [comment]
This is part of the Fetch API, and not really something that this library can handle. You could add a request interceptor that uses [`Request.clone`](https://developer.mozilla.org/en-US/docs/Web/API/Request/clone) to clone and store the request before it's sent.

**Comment by dilvish4ever** [comment]
Same situation, no request `body`, futhermore `bodyUsed=false` in cloned request :(

**Comment by wmathes** [comment]
Encountered it yesterday and think it IS a bug in Aurelia somewhere.

When just using native/polyfill  .fetch("someBodyWith404.json")i can access the response's body via response.json() just fine. I can't however do that via an interceptor in Aurelia as the body stream will always be read already.

**Comment by bryanrsmith** [comment]
@dilvish4ever `bodyUsed=false` is what I'd expect in a request cloned before sending. Do you have a plunker I could check out?

@wmathes I think that's a bit different-- we're discussing a need to read the *request* body after the request has already been sent. It sounds like you need to clone the response before reading its body. If you have a code sample I might be able to help.
