### ISSUE TITLE
Can't read json from multiple interceptors

### ISSUE THREAD

**Issue by snortblt** [aurelia/fetch-client#48]
If multiple interceptors are installed in the fetch client, only one of them can call response.json(). The second one to call causes an "already read" exception. I suppose that makes some sense from a stream reading perspective, but it doesn't make sense if multiple interceptors are allowed. Obviously, it would not be uncommon to want to read at least part of the response in both places.

Maybe a `configure `option for caching the json in the client for mulitple access would be a solution?

**Comment by bryanrsmith** [comment]
Interceptors are chained such that the resolution of one is propagated to the next. I think altering the data passed to a downstream interceptor would be unexpected. Would this be solved simply by cloning the response before reading its body?

**Comment by doktordirk** [comment]
Or response.json(true) returns a clone

**Comment by EisenbergEffect** [comment]
Any thoughts on how to resolve this?

**Comment by bryanrsmith** [comment]
Response bodies can only be read once, so you just need to clone the response if you want to read it multiple times. `response.clone().json()`

**Comment by EisenbergEffect** [comment]
Ok, so we'll just close this then :)
