### ISSUE TITLE
Can't read json of response in interceptor

### ISSUE THREAD

**Issue by svzosorio** [aurelia/fetch-client#50]
Usign interceptors in angular when the request is error I show on display the error, but now usign this library in responseError Method when I call to response.json I receive `Uncaught (in promise) SyntaxError: Unexpected token N` error

How is the best form to use the interceptors to display error messages whitout promises ?

**Comment by bryanrsmith** [comment]
It sounds like the response body you're trying to deserialize is not valid JSON. If you can provide more information I might be able to help.
