### ISSUE TITLE
Different Services Injected on same Screen

### ISSUE THREAD

**Issue by DiegoGallegos4** [aurelia/fetch-client#55]
Here is my project: https://github.com/DiegoGallegos4/aurelia-test

It is connected to a real server but I think that dummy data can be passed to it instead of fetching on the service. The issue is the following: 

1. Whenyou navigate to ** departmento ** route. The DepartmentService is injected. 
2. When you navigate to **empleado** route. The EmpleadoService is injected.
3. If you navigate back to departmento. The EmpleadoService is injected.

You can repeat this and watch this happening.

**Comment by EisenbergEffect** [comment]
From what it looks like, you are getting the same HttpClient instance, since that is a singleton by default. To change this behavior, in your main.js you can register it as transient.

```javascript
aurelia.use.transient(HttpClient);
```
