### ISSUE TITLE
Requests are sent to incorrect hostname

### ISSUE THREAD

**Issue by istrau2** [aurelia/fetch-client#56]
Somehow my fetch requests are sometimes being sent to incorrect hostnames:

```
1) localhost:3000/api/method //correct
2) localhost:3000/dashboard/api/method //incorrect
```
I have tried to track when and why this happens but I can't seem to figure it out. How can I ensure that my requests are always sent to window.location.host + httpClient.baseUrl + 'path/to/endpoint/ when I call httpClient.fetch('path/to/endpoint', params)?

**Comment by EisenbergEffect** [comment]
Are you using push state? If so, have you set the base tag in your html?

**Comment by istrau2** [comment]
@EisenbergEffect Yes, I have the base tag set as:

```
    <base href="/">
```

After playing with it more it seems that the extra /dashboard in the request url depends on the initial request I make for the page itself from the server (which always serves index.html).

If I request 'localhost:3000/dashboard' -> I get incorrect fetch urls
If I request 'localhost:3000/dashboard/users' -> I get correct fetch urls.

my route structure is as follows:

app -> ('/', 'public'), ('/dashboard', 'dashboard')
dashboard -> ('/', 'home'), ('/users', 'users')
users -> ('/', 'users-list'), ('/detail/:id', 'user-detail')

To be clear the routing seems to be working fine:
localhost:3000/dashboard takes me to home
localhost:3000/dashboard/users takes me to users

just getting these weird urls in the fetch client. I was expecting to just get localhost:3000/api/method (api is my defaultUrl on the client).

**Comment by istrau2** [comment]
@EisenbergEffect 

Hmmmm, actually it seems you are right (you can ignore my post above). I had the base tag in my index.html's body but upon examining the rendered source it is gone. Apparently, the something in webpack (probably the loader) is replacing the contents of the body. 

I added it the tag to my app.html and that seems to have solved the issue.

Thanks.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you comment on this?

**Comment by EisenbergEffect** [comment]
Oh, oops didn't see your other post ;)
Actually, it may be Aurelia replacing your body. But the head is the best place to put the base tag. Glad that fixed your issue!

**Comment by EisenbergEffect** [comment]
@istrau2 Would you be interested in contributing to our docs. In the fetch repo, the docs folder contains some documentation on the fetch client. It would be nice to have an info block on setting the base tag to help users of fetch from hitting this in the future. Are you interested in PR'ing that?

**Comment by istrau2** [comment]
@EisenbergEffect I would like to yes, I have a ton going on this week (especially today). I will try and do it (just can't promise I will get to it today).

**Comment by EisenbergEffect** [comment]
Sounds good! Thanks!
