### ISSUE TITLE
Upload Progress

### ISSUE THREAD

**Issue by lukechilds** [aurelia/fetch-client#57]
It would be great if I could register a progress callback for file uploads. I think (according to this https://github.com/aurelia/http-client/issues/104) `http-client ` has `.withProgressCallback()`. Is there an equivalent for `fetch-client`?

**Comment by EisenbergEffect** [comment]
Unfortunately, no. This is a limitation of the Fetch API spec at the moment. If you need that functionality, we usually recommend that you use the http-client. You can read more about fetch here: http://aurelia.io/docs.html#/aurelia/fetch-client/1.0.0-beta.1.2.2/doc/article/http-services/2 There's a section in the docs on "limitations".

**Comment by lukechilds** [comment]
Sorry, I missed that. Thanks 👍
