### ISSUE TITLE
Additional configuration

### ISSUE THREAD

**Issue by mttmccb** [aurelia/fetch-client#58]
Would it make sense to add an option to the config of fetch client to get the json so instead of

```
httpClient.fetch('package.json')
    .then(response => response.json())
    .then(data => {
        console.log(data.description);
    });
```

You could do something like this in the configure

```
httpClient.configure(config => {
    config
        .getJsonFromResponse()
});
```

and do this instead

```
httpClient.fetch('package.json')
    .then(data => {
        console.log(data.description);
    });
```

If you're accessing a json api you'll probably end parsing json on every request anyway...

**Comment by zsvanderlaan** [comment]
+1 for smart/configurable defaults to reduce boilerplate.

**Comment by bryanrsmith** [comment]
I think this would work fine today with a response interceptor. Something like...

```js
client.configure(config =>
    config.withInterceptor({
        response: (response) => response.json()
    })
);
```

**Comment by zsvanderlaan** [comment]
Thanks for the example, this is a very helpful solution!

**Comment by bryanrsmith** [comment]
No problem!
