### ISSUE TITLE
json util ie8

### ISSUE THREAD

**Issue by RWOverdijk** [aurelia/fetch-client#59]
Hey!

I just got an interesting question concerning our [aurelia-api](https://github.com/SpoonX/aurelia-api) module. We use the [json util](https://github.com/aurelia/fetch-client/blob/master/src/util.js) on [the request body](https://github.com/SpoonX/aurelia-api/blob/master/src/rest.js#L40,L42) which appears to not work in some version of IE (9 and lower, 10 not sure) because they don't support Blob.

Why does util make it a blob to begin with? I'm trying to understand if changing it to JSON.stringify() would have any implications.

Not sure if this is a bug, a choice or a misunderstanding.

**Comment by bryanrsmith** [comment]
`JSON.stringify()` would work just as well, so long as you set the content-type header appropriately. The Blob lets us use a single object that acts as the body, but causes the content-type header to be set as well.

**Comment by RWOverdijk** [comment]
Ah so this is just a two in one solution. In that case I'll go with stringify for browser support. Thanks for the prompt answer!

**Comment by doktordirk** [comment]
@bryanrsmith  yeah, that's not gonna fly with me. you offer .json(), you support it. i searched and that this is the only place where Blob is used without any check first. PRed a fix
