### ISSUE TITLE
Issue with documentation rendering of links with apostrophes in the label

### ISSUE THREAD

**Issue by effervescentia** [aurelia/fetch-client#60]
Probably an issue with whatever converts your markdown to html. Documented here as it's where I noticed links suffering from the actual problem, may be happening elsewhere.

<img width="926" alt="github preview" src="https://cloud.githubusercontent.com/assets/3784470/15269447/8e24d734-19cc-11e6-8d5d-9226716fd7aa.png">

<img width="1015" alt="aurelia io documentation" src="https://cloud.githubusercontent.com/assets/3784470/15269449/960dc4c4-19cc-11e6-861b-2a70c6d9d649.png">

<img width="655" alt="aurelia io html" src="https://cloud.githubusercontent.com/assets/3784470/15269452/9c2d301a-19cc-11e6-9838-d6e486938cba.png">

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/app-documentation #40](https://github.com/aurelia/app-documentation/issues/40) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by EisenbergEffect** [comment]
We moved this issue to an internal repo where we can track the fix. Thanks!

**Comment by effervescentia** [comment]
Yeah, I imagined it was a larger issue, just didn't know where to document it 😜 glad to be of help
