### ISSUE TITLE
charset issue

### ISSUE THREAD

**Issue by dpinart** [aurelia/fetch-client#64]
Hi,

We have an application that gets data from a remote backend encoded with charset ISO-8859-1. With jQuery ajax we could set the dataType settings paramater to "json" and it automatically transforms the received stream to UTF-8. Is there anyway to handle this issue with the fetch client plugin?

**Comment by Jaswanth75** [comment]
Hi @dpinart ,

Past one week I have been dealing with request and response objects in fetch client.
May be I can be of any help.

Can you please specify what input you are passing and what output you are expecting for the fetch client to handle ?

**Comment by dpinart** [comment]
Hi @Jaswanth75 
Thanks for your interest
I'm just performing a get verb. The response is a json stringfied coming from the backend (SAP ERP). The backend is configured to use charset ISO-8859-1 but json works with UTF-8 and several characters like diacritics, euro symbol and other are not being printed well in the screen

**Comment by Jaswanth75** [comment]
Hi @dpinart ,

Can you try this piece of code...
$.ajax({
    url: '...',
    contentType: 'Content-type: text/plain; charset=iso-8859-1',
    // This is the imporant part!!!
    beforeSend: function(jqXHR) {
        jqXHR.overrideMimeType('text/html;charset=iso-8859-1');
    }
})

**Comment by dpinart** [comment]
Hi @Jaswanth75 
I could handle with iso-8859-1 encoding with jquery.ajax method by just setting dataType option to 'json". I'm getting rid of jquery and would like to get a similar option with fetch-client

**Comment by EisenbergEffect** [comment]
This isn't an issue with our library, per se. It's an issue of configuring fetch correctly. I believe that the above example shows that a content type specification is in order so I would suggest trying that with our fetch client by adding the header.
