### ISSUE TITLE
How to configure request headers?

### ISSUE THREAD

**Issue by JamesReate** [aurelia/fetch-client#8]
The documentation is pretty clear on how to set http-client request headers globally, but not for the fetch-client... How do we go about setting for example the Authorization Header for all requests with fetch-client?

**Comment by bryanrsmith** [comment]
Hi @JamesReate. Sorry I haven't had time to get documentation on the new fetch-client in an official location. Here's some preliminary info I put together in the meantime: https://gist.github.com/bryanrsmith/14caed2015b9c54e70c3

You should be able to configure default headers like so:

```js
httpClient.configure(config => {
    config.withDefaults({
        headers: {
            'My-Custom-Header': 'WooHoo'
        }
    })
});
```

**Comment by JamesReate** [comment]
Great thank you Bryan just what I needed

-----Original Message-----

**Comment by mreiche** [comment]
@bryanrsmith

Using withDefaults() overwrites headers from the standardConfiguration()
```fetchClient.configure(config => {
	config.useStandardConfiguration();
});
```
Cookie-Header is present. But when setting defaults:
```
fetchClient.configure(config => {
	config.useStandardConfiguration();
	config.withDefaults({
		headers: {
			'X-XSRF-TOKEN':Cookies.get('XSRF-TOKEN'),
			'Accept': 'application/json'
		}
	});
});
```
The X-XSRF-TOKEN is present, but Cookie is missing.
Shall I use interceptors to add my custom headers to the default configuration?

**Comment by bryanrsmith** [comment]
@mreiche You can either call `.useStandardConfiguration()` after `.withDefaults()`, or you can add `credentials: 'same-origin'` to your defaults.

**Comment by mreiche** [comment]
Thanks!

**Comment by huc1810** [comment]
Hello! Hope you are doing great!

I am basically new to Aurelia! 

I am using the fetch-client to upload files and images, sending headers with my form data, but don't know why my headers are being changed from Content-Type to content-type for example, and this is apparently causing an error in the API. Do you know how to avoid this or is this a normal behavior?  

   headers.set('Accept', '*/*');
   headers.set('Content-Type', 'multipart/form-data');
   const payload = await this.http.fetch(path, {
      method: 'post',
      body: item,
      headers: headers
    }).then(response => response.json())
      .catch(err => err);

Thanks

**Comment by MarkHerhold** [comment]
@huc1810 I'm not sure if this is your problem, but make sure you are converting your body to a proper JSON object that the fetch client understands.

```js
import { HttpClient, json } from 'aurelia-fetch-client';

const payload = await this.http.fetch(path, {
  method: 'post',
  body: json(item), <--- be sure to call json() on your body before sending
  headers: headers
})
.then(response => response.json())
.catch(err => console.error(err));
```

**Comment by alastair-mcdonald** [comment]
I am trying to use .withInterceptor to add an Authorization header with a refreshed bearer token. At a minimum I would like to do the following within .withInterceptor...
```
export class ClientService
{
    public BaseUrl: string;
    private http: HttpClient;
    private apiTokenService: ApiToken;
    private token: BearerToken;
	
...
	this.http.configure((config) =>
	{
		config
			.withBaseUrl('http://localhost/MyApiName.Api')
			.withDefaults(
			{
				credentials: 'same-origin',
				headers: {
					'Accept': 'application/json',
					'X-Requested-With': 'Fetch'
				}
			})
			.withInterceptor({
				request(request)
				{
					if (request.headers.has('Authorization'))
					{
						request.headers.delete('Authorization');
					}
					request.headers.append('Authorization', 'Bearer ' + this.token.accessToken);			
					
					return request;
				}
			});
	});
...
}
```
However `this` is the `Request` object, not the containing class, and so does not contain `this.token`. How do I access `this.token` variable in the containing class?

 A much better solution would be to call `this.apiTokenService.getToken()` so I always get a fresh token, however withIntercedptor's request method must return either a Request or Promise<Request> and I haven't figured out how to chain promises in such a way as to get the token by using a promise and return a request object. If you can point out how to make an async call within the request method, then add a header, then return a Request object I'd be very grateful.

**Comment by alastair-mcdonald** [comment]
I got `.withInterceptor` working as follows. I had to create a scoped `ApiToken` variable. The only problem now is that it is not unit testable as with this setup I can't use an injected `ApiToken`. May open a new issue to look at this.

```
.withInterceptor({                    
	request(request)
	{

		let tokenService = new ApiToken(new HttpClient());
		let tokenPromise : Promise<BearerToken> = tokenService.getToken();                     

		return tokenPromise
			.then((token: BearerToken) =>
			{

				request.headers.append('Authorization', 'Bearer ' + token.accessToken);
				return request;
			})

	}
	});
```

**Comment by matik12** [comment]
@alastair-mcdonald look at my implementation here - https://github.com/matik12/aurelia-oauth/blob/master/src/oauth-interceptor.ts 
Interceptor is simply an object having proper methods defined that are invoked in the the request promise chain pipeline, so you can easily create a class for interceptor with injectable constructor parameters and then unit test what we need.

**Comment by alastair-mcdonald** [comment]
@matik12  thank you for this excellent information and code - a very useful pointer in the right direction.
