### ISSUE TITLE
config.rejectErrorResponses - lots of console warnings

### ISSUE THREAD

**Issue by ry8806** [aurelia/fetch-client#87]
**I'm submitting a bug report**

* **Library Version:**
1.1.1

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
7.7.1

* **NPM Version:**
4.3.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
developer console gets cluttered with warnings when setting the `http-fetch-client` config to use `config.rejectErrorResponses();`
![aurelia-http-fecth-promise-warn](https://cloud.githubusercontent.com/assets/10958000/23861694/b8bb7a14-0802-11e7-93d3-f19c8227d45d.png)

**Expected/desired behavior:**
Not to have `console.warn`'s being written when trying to get the fetch client to reject non 200-299 http status codes.

I understand that there are two ways to "fix" (stop) this. One is to satisfy the BlueBird requirement [here](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-rejected-with-a-non-error), this would require Aurelia creating an instance of that response as an `Error` object.
The second would be to review the use of BlueBird promises. I was under the impression after reading [this article](https://www.danyow.net/edge-promise-perf/) that BlueBird was included as a polyfill for Edge, is this a correct assumption? Or have i read too much into that blog post?

**Comment by EisenbergEffect** [comment]
BlueBird is primarily there due to an Edge promise performance regression.

**Comment by ry8806** [comment]
@EisenbergEffect thanks, it looks as though the referenced "User Voice" issue was "fixed/improved" in Aug 2016 - are there now plans to remove BlueBird from Aurelia as all Edge browsers are primarily self-updating?

**Comment by ry8806** [comment]
Also, is this only supposed to polyfill in Edge? because at the moment it's there in all browsers

**Comment by CasiOo** [comment]
I believe you can configure Bluebirdjs to not give you any console warnings like those. Try and read the configuration section of Bluebird.

**Comment by ry8806** [comment]
@CasiOo yes, i've found that in their docs, however I wouldn't call that a solution. By turning that on to avoid the above warnings, I might miss out on some other warnings which might be important

**Comment by EisenbergEffect** [comment]
We did some work in the Aurelia setups so that it's not much easier to remove or re-configure Bluebird if you do not want/need it.
