### ISSUE TITLE
Invalid TypeScript type definitions

### ISSUE THREAD

**Issue by atsu85** [aurelia/fetch-client#9]
probably this line https://github.com/aurelia/fetch-client/blob/master/dist/aurelia-fetch-client.d.ts#L2
should probably be
`import 'core-js';`

But there are more problems with the definitions after fixing it:

> jspm_packages\github\aurelia\fetch-client@0.1.1\aurelia-fetch-client.d.ts(6,32): error TS2304: Cannot find name 'undefined'.
jspm_packages\github\aurelia\fetch-client@0.1.1\aurelia-fetch-client.d.ts(7,31): error TS2304: Cannot find name 'undefined'.
jspm_packages\github\aurelia\fetch-client@0.1.1\aurelia-fetch-client.d.ts(8,35): error TS2304: Cannot find name 'undefined'.
jspm_packages\github\aurelia\fetch-client@0.1.1\aurelia-fetch-client.d.ts(9,32): error TS2304: Cannot find name 'undefined'.
jspm_packages\github\aurelia\fetch-client@0.1.1\aurelia-fetch-client.d.ts(14,19): error TS2304: Cannot find name 'BufferSource'.
jspm_packages\github\aurelia\fetch-client@0.1.1\aurelia-fetch-client.d.ts(14,45): error TS2304: Cannot find name 'URLSearchParams'.

I haven't investigated how d.ts files are generated, but it looks like generator doesn't understand function return type from this file
https://github.com/aurelia/fetch-client/blob/master/src/interfaces.js#L4-L10

and because of it `undefined` is used as a return type (that is even not a valid return type)

**Comment by EisenbergEffect** [comment]
We discovered a bug in the generator for interface method return types just last night. We submitted a PR to the project to fix it already. As soon as it is merged and released we will fix this and release. If that doesn't happen in a timely fashion, we have some other options we can take. Please hand with us while we try to engage the community and contribute back to other projects. Thank you!

**Comment by EisenbergEffect** [comment]
Fixed in the next release.
